DROP TABLE USUARIOS;
CREATE TABLE USUARIOS
(USERNAME 	VARCHAR2(30) PRIMARY KEY,
 PASSWORD 	VARCHAR2(30) NOT NULL,
 CREATED 	DATE NOT NULL,
 ACCESOS 	NUMBER(5));
insert into usuarios values
('ANTONIO','MARTIN',TO_DATE ('2022-11-16','YYYY-MM-DD'),0);
insert into usuarios values
('USUARIO1','USUARIO1',TO_DATE ('2000-01-30','YYYY-MM-DD'),0);
insert into usuarios values
('USUARIO2','USAURIO2',TO_DATE ('1997-07-01','YYYY-MM-DD'),0);
COMMIT;
